"use client";
import { useState } from 'react';
import Link from 'next/link';
import { ItemCategoryIcon } from '@/components/item-category-icon';
import { ArrowLeft, ArrowRight, ShieldCheck, Pencil, CircleHelp, FileText, Headphones, Check } from 'lucide-react';
import { OwnershipShell } from '@/components/ownership-shell';
import { useMock } from '@/components/mock-provider';
import { Documents } from '@/components/document-viewer';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { fieldLabels, dateLabel, warrantyStatus, type ItemFields } from '@/lib/mock-data';
export function ItemDetail({id,problem=false}: {id:string;problem?:boolean}) {
 const {items,updateItem}=useMock();const item=items.find(i=>i.id===id||i.sampleKey===id);
 const [saving,setSaving]=useState(false);
 const [editing,setEditing]=useState(false);const [draft,setDraft]=useState<ItemFields|null>(null);const [error,setError]=useState('');
 const [issue,setIssue]=useState('');const [savedIssue,setSavedIssue]=useState('');const [copied,setCopied]=useState(false);
 if(!item)return <OwnershipShell><div className="page-wrap"><h1>Item not available.</h1><p className="intro">This item is not in this tab’s demo collection. Refreshing clears added items and restores the samples.</p><Button asChild className="action"><Link href="/">Back to dashboard</Link></Button><Button asChild variant="outline" className="ml-3"><Link href="/items/new">Add an item</Link></Button></div></OwnershipShell>;
 const status=warrantyStatus(item);
 async function save(event:React.FormEvent){event.preventDefault();if(!draft||!item||saving)return;setSaving(true);try{await updateItem(item.id,draft);setError('');setEditing(false);}catch(cause){setError(cause instanceof Error?cause.message:'Could not save details.');}finally{setSaving(false);}}
 return <OwnershipShell><div className="page-wrap">
  <Link href={problem?'/items/'+id:'/'} className="text-link mb-7"><ArrowLeft size={18}/>{problem?item.name:'Dashboard'}</Link>
  <header className="page-heading"><div><p className="eyebrow">{problem?'SOMETHING’S WRONG':'YOUR OWNERSHIP RECORD'}</p><h1>{problem?'Let’s find what you need.':item.name}</h1><p className="intro">{problem?item.name+' · Documents and next steps, together.':(item.brand+' '+item.model+' · '+(item.location||'Location not set'))}</p></div>{!problem&&<Button className="action" variant="outline" onClick={()=>{setDraft({...item});setEditing(true);setError('')}}><Pencil/> Edit details</Button>}</header>
  {!problem&&<section className="detail-hero"><ItemCategoryIcon category={item.category}/><div><span className="status-badge"><Check size={14}/> Confirmed record</span><h2>Your item.<br/>The whole story.</h2><p>{item.retailer || 'Retailer not recorded'} · {dateLabel(item.purchaseDate)}</p><div className="mini-facts"><div><small>Purchase price</small><strong>{item.price?'₹'+Number(item.price).toLocaleString('en-IN'):'Not recorded'}</strong></div><div><small>Warranty</small><strong>{status}</strong></div></div><Button asChild className="action"><Link href={'/items/'+id+'/problem'}><CircleHelp/> Something’s wrong <ArrowRight/></Link></Button></div></section>}
  {problem?<><div className="problem-grid"><section className="panel lime"><ShieldCheck/><p className="eyebrow mt-5">WARRANTY STATUS</p><h2>{status==='Unknown'?'Coverage not confirmed':status==='Active'?'Within sample coverage':'Sample coverage expired'}</h2><p>{item.warrantyExpiry?'Expiry: '+dateLabel(item.warrantyExpiry):'Add warranty evidence to understand the coverage.'}</p><p className="text-sm">Based on confirmed demo values and the fixed demo date. This does not establish real warranty eligibility.</p><Button variant="outline" onClick={()=>{setDraft({...item});setEditing(true);setError('')}}>Review warranty details</Button></section><section className="panel"><FileText/><h2 className="mt-5">Documents</h2><p className="mb-5">Keep the source evidence close at hand.</p><Documents documents={item.documents}/></section></div>
   <div className="problem-grid mt-6"><section className="panel"><Headphones/><h2 className="mt-5">Customer care</h2><p>No verified customer-care number or official support link is recorded for this sample item.</p><p>Use the contact printed on your original packaging or warranty document.</p><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText([item.name,item.brand,item.model,item.serial,item.retailer,item.purchaseDate].filter(Boolean).join('\n'));setCopied(true);}catch{setCopied(false);setError('Clipboard unavailable. You can select the product details on the item page.');}}}>{copied?'Copied item details':'Copy item details for support'}</Button><p role="status" className="text-sm">{copied?'Ready to paste into your own support message.':''}</p></section>
   <section className="panel violet"><CircleHelp/><h2 className="mt-5">Troubleshooting</h2><p>No verified troubleshooting guide is saved for this item. Product-specific repair steps are unavailable in this demo.</p><label htmlFor="issue">What’s happening?</label><textarea id="issue" className="text-source" value={issue} onChange={e=>setIssue(e.target.value)} maxLength={2000} placeholder="Describe the issue for your support conversation…"/><Button variant="outline" disabled={!issue.trim()} onClick={()=>setSavedIssue(issue.trim())}>Save issue note</Button>{savedIssue&&<div className="mt-4 rounded-xl bg-white p-4" role="status"><strong>Note saved for this visit</strong><p className="whitespace-pre-wrap break-words">{savedIssue}</p></div>}</section></div></>:<Tabs defaultValue="overview" className="mt-9"><TabsList className="h-12"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="documents">Documents ({item.documents.length})</TabsTrigger><TabsTrigger value="timeline">Timeline</TabsTrigger></TabsList><TabsContent value="overview" className="mt-5"><section className="panel"><h2 className="mb-6">Item details</h2><dl className="fields-grid">{(Object.keys(fieldLabels) as (keyof ItemFields)[]).map(key=><div key={key} className="fact"><dt>{fieldLabels[key]}</dt><dd>{key==='purchaseDate'||key==='warrantyExpiry'?dateLabel(item[key]):item[key]||'Not recorded'}</dd></div>)}</dl><p className="mt-6 text-sm text-muted-foreground">Initial records are synthetic fixtures. Edits and newly created records reflect your explicit confirmation in this tab’s collection. Items, edits, files and source text are cleared on refresh.</p></section></TabsContent><TabsContent value="documents" className="mt-5"><section className="panel"><h2 className="mb-5">Your documents</h2><Documents documents={item.documents}/></section></TabsContent><TabsContent value="timeline" className="mt-5"><section className="panel"><h2>Ownership timeline</h2><ol className="timeline"><li><strong>Purchase</strong><span>{dateLabel(item.purchaseDate)}</span></li><li><strong>Record confirmed</strong><span>{item.createdAt ? new Date(item.createdAt).toLocaleDateString('en-IN') : 'This visit'}</span></li><li><strong>Warranty expiry</strong><span>{dateLabel(item.warrantyExpiry)}</span></li></ol><p>No maintenance or service schedule has been recorded.</p></section></TabsContent></Tabs>}
  {error&&!editing&&<p role="alert" className="error">{error}</p>}
  <Dialog open={editing} onOpenChange={value=>{if(!saving)setEditing(value)}}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogTitle>Edit confirmed details</DialogTitle><DialogDescription>Save explicitly to update this item for this visit. Refreshing clears your edits.</DialogDescription><form onSubmit={save}><div className="fields-grid">{draft&&(Object.keys(fieldLabels) as (keyof ItemFields)[]).map(key=><div key={key}><label htmlFor={'edit-'+key}>{fieldLabels[key]}</label><Input id={'edit-'+key} value={draft[key]} disabled={saving} required={key==='name'} type={key==='purchaseDate'||key==='warrantyExpiry'?'date':key==='price'?'number':'text'} min={key==='price'?'0':undefined} step={key==='price'?'0.01':undefined} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></div>)}</div>{error&&<p role="alert" className="error">{error}</p>}<div className="mt-6 flex gap-3"><Button type="button" variant="outline" disabled={saving} onClick={()=>setEditing(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? 'Saving…' : 'Save details'}</Button></div></form></DialogContent></Dialog>
 </div></OwnershipShell>;
}
